<a href="https://colab.research.google.com/github/joshuashaji30-star/Ict_DSA_works/blob/main/Data_Acquisition_CaseStudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Load SpaceX Launch Data From API

In [98]:
import requests
import pandas as pd

In [99]:


url = "https://api.spacexdata.com/v4/launches"
data = requests.get(url).json()

df = pd.DataFrame(data)
df = df[['name', 'date_utc', 'success', 'details', 'rocket']]
df

,name,date_utc,success,details,rocket
0,FalconSat,2006-03-24T22:30:00.000Z,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb
1,DemoSat,2007-03-21T01:10:00.000Z,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb
2,Trailblazer,2008-08-03T03:34:00.000Z,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb
3,RatSat,2008-09-28T23:15:00.000Z,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb
4,RazakSat,2009-07-13T03:35:00.000Z,True,None,5e9d0d95eda69955f709d1eb
...,...,...,...,...,...
200,Transporter-6,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec
201,TTL-1,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec
202,WorldView Legion 1 & 2,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec
203,Viasat-3 & Arcturus,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69974db09d1ed
204,O3b mPower 3.4,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec

In [97]:
df['date_utc'] = pd.to_datetime(df['date_utc'])
df['year'] =df['date_utc'].dt.year
df[['date_utc','year']]

                     date_utc  year
0   2006-03-24 22:30:00+00:00  2006
1   2007-03-21 01:10:00+00:00  2007
2   2008-08-03 03:34:00+00:00  2008
3   2008-09-28 23:15:00+00:00  2008
4   2009-07-13 03:35:00+00:00  2009
..                        ...   ...
200 2022-12-01 00:00:00+00:00  2022
201 2022-12-01 00:00:00+00:00  2022
202 2022-12-01 00:00:00+00:00  2022
203 2022-12-01 00:00:00+00:00  2022
204 2022-12-01 00:00:00+00:00  2022

[205 rows x 2 columns]

#Load Rocket Metadata

In [69]:
url="https://api.spacexdata.com/v4/rockets"
data=requests.get(url).json()

In [70]:
r_df=pd.DataFrame(data)

In [90]:
r_df = r_df[['id', 'name', 'type', 'active', 'stages']]
r_df

                         id          name    type  active  stages
0  5e9d0d95eda69955f709d1eb      Falcon 1  rocket   False       2
1  5e9d0d95eda69973a809d1ec      Falcon 9  rocket    True       2
2  5e9d0d95eda69974db09d1ed  Falcon Heavy  rocket    True       2
3  5e9d0d96eda699382d09d1ee      Starship  rocket   False       2

#Merge Launch and Rocket data

In [89]:
merged_df = pd.merge(
    df,
    r_df,
    left_on='rocket',
    right_on='id',
    how='left'
)

merged_df.rename(columns={
    'name_x': 'launch_name',
    'name_y': 'rocket_name'
}, inplace=True)

merged_df.drop(columns=['id'], inplace=True)
merged_df

,launch_name,date_utc,success,details,rocket,year,rocket_name,type,active,stages
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,Falcon 1,rocket,False,2
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,Falcon 1,rocket,False,2
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,Falcon 1,rocket,False,2
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,Falcon 1,rocket,False,2
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009,Falcon 1,rocket,False,2
...,...,...,...,...,...,...,...,...,...,...
200,Transporter-6,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,True,2
201,TTL-1,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,True,2
202,WorldView Legion 1 & 2,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,True,2
203,Viasat-3 & Arcturus,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69974db09d1ed,2022,Falcon Heavy,rocket,True,2
204,O3b mPower 3.4,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,True,2

#Add Simulated Country Column

In [91]:
import random

In [96]:
countries = ['USA', 'Russia', 'India', 'China', 'France']

merged_df['country'] = [random.choice(countries) for _ in range(len(merged_df))]
merged_df[['launch_name','country']]

                launch_name country
0                 FalconSat     USA
1                   DemoSat     USA
2               Trailblazer  Russia
3                    RatSat     USA
4                  RazakSat   China
..                      ...     ...
200           Transporter-6  France
201                   TTL-1  Russia
202  WorldView Legion 1 & 2  Russia
203     Viasat-3 & Arcturus     USA
204          O3b mPower 3.4   India

[205 rows x 2 columns]

#Store Merged data in sqlite3

In [ ]:
import sqlite3

In [102]:
conn = sqlite3.connect("spacex.db")

merged_df.to_sql("launches", conn, if_exists="replace", index=False)

205

#SQL Analysis

##Launches by country

In [103]:
q1 = """
SELECT country, COUNT(*) AS All_launches
FROM launches
GROUP BY country
ORDER BY All_launches DESC;
"""
print(pd.read_sql(q1, conn))

  country  All_launches
0  Russia            51
1     USA            41
2  France            39
3   India            38
4   China            36

##Year with highest launch

In [104]:
q2 = """
SELECT year, COUNT(*) AS All_launches
FROM launches
GROUP BY year
ORDER BY All_launches DESC
LIMIT 1;
"""
print(pd.read_sql(q2, conn))

   year  All_launches
0  2022            62

##Top 5 missions by Launch count

In [105]:
q3 = """
SELECT launch_name, COUNT(*) AS launch_count
FROM launches
GROUP BY launch_name
ORDER BY launch_count DESC
LIMIT 5;
"""
print(pd.read_sql(q3, conn))

                 launch_name  launch_count
0  ispace Mission 1 & Rashid             1
1                       ZUMA             1
2     WorldView Legion 1 & 2             1
3        Viasat-3 & Arcturus             1
4                    USSF-44             1